version: "2.1"

services: 
    ##Container providing a local MSSQL db instance
    dba1:
        container_name: 'mssql-db'
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: Qwe12312
        volumes:
            - sqlsystem:/var/opt/mssql/data
            - sqluser:/var/opt/mssql/sqlserver
            - sqlbackups:/var/opt/mssql/backups
