version: "3.8"

services: 
    ##Container providing a local MSSQL db instance
    svr003:
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: Qwe12312
        image: solar/base/mssql_server_2017/local
        ports:
            - 1433:1433
        volumes:
            - mssqlserver_volume:/var/opt/mssql 
volumes:
    mssqlserver_volume:
    