version: "3.4"

services: 
    ##Container providing a local MSSQL db instance
    sqlserver:
        container_name: 'mssql-db'
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: Qwe12312
        volumes:
            - mssql-server-linux-data:/var/opt/mssql/data
            - mssql-server-linux-data:/var/opt/mssql/log

volumes:
  mssql-server-linux-data:
 
